# Generated by Django 5.1.4 on 2025-06-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0004_userprofile_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
